site_name: 我的文档
site_author: MonkeyIU
site_description: MkDocs + Material 示例 

theme: 
  name: material 
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MonkeyIU

plugins:
  - search
  - minify
  - mermaid2
  - git-revision-date:
      enabled: true
      type: datetime
      fallback_to_build_date: true
